### ISSUE TITLE
Sum square of affine expressions - aro

### ISSUE THREAD

**Issue by GalPerelman** [XiongPengNUS/rsome#59]
Is there a way to use `rsome.sumsqr` or `rsome.square` with ldr variables?

For example, consider the following:
```
import rsome
from rsome import ro

model = ro.Model()

x = model.ldr((n, T))
z = model.rvar((n, T))
uset = (rsome.norm(z.reshape(-1), 2) <= 1)

for t in range(1, T):
    x[:, t].adapt(z[:, :t])

model.minmax(rsome.sumsquare(c * x), nom_uset)
```

This code raises the following error:
`AttributeError: 'RoAffine' object has no attribute 'square'`

Alternatively, does ROSME allow the definition of gurobi [SOS constraints](https://www.gurobi.com/documentation/current/refman/sos_constraints.html#:~:text=A%20Special%2DOrdered%20Set%2C%20or,a%20given%20list%20can%20take.)?

The purpose of these questions is to model a quadratic objective function for adjustable robust optimization problem
In case squared `ldr` variables are not available the second option is to model a piecewise linear objective by using SOS constraints

**Comment by XiongPengNUS** [comment]
Hi @GalPerelman, unfortunately, RSOME does not support the square or norm of expressions involving linear decision rule or random variables. Please check the general RO formulation discussed at [here](https://xiongpengnus.github.io/rsome/ro_rsome#section2.1), the objective function or constraints must be **biaffine** in the decision variable $\pmb{x}$ and random variable $\pmb{z}$, so that we can reformulate the robust model into its tractable deterministic equivalence. Squares or any other nonlinear operations do not comply with this general format so in general, there is no easy way to support them in RSOME.
